/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;


import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import org.json.simple.JSONObject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
/**
 *
 * @author chuna
 */
public class MyWeatherGUI extends javax.swing.JFrame {
    private JSONObject weatherData;
    /**
     * Creates new form MyWeatherGUI
     */
    public MyWeatherGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("src/image/100clear.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        soilTemperature = new javax.swing.JLabel();
        cloudCover = new javax.swing.JLabel();
        humidityImage = new javax.swing.JLabel();
        windspeeds = new javax.swing.JLabel();
        windspeedText = new javax.swing.JLabel();
        humidityText = new javax.swing.JLabel();
        windspeedImage = new javax.swing.JLabel();
        humidityPercent = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        weatherConditionDesc = new javax.swing.JLabel();
        temperatureText = new javax.swing.JLabel();
        weatherConditionImage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        myLocation = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Weather");
        setBounds(new java.awt.Rectangle(25, 25, 25, 25));
        setMaximumSize(new java.awt.Dimension(450, 650));
        setMinimumSize(new java.awt.Dimension(450, 650));
        setPreferredSize(new java.awt.Dimension(459, 662));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(219, 246, 246));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 650));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("12/12/2023");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 50, 80, 16);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 40, 40, 33);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("VỊ TRÍ CỦA TÔI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 160, 22);

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel4.setLayout(null);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(0, 155, 390, 3);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cloud_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(210, 180, 24, 24);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Độ che phủ mây");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(240, 170, 127, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thermostat_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jPanel4.add(jLabel12);
        jLabel12.setBounds(210, 240, 20, 24);

        soilTemperature.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        soilTemperature.setText("30℃");
        jPanel4.add(soilTemperature);
        soilTemperature.setBounds(240, 260, 70, 21);

        cloudCover.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cloudCover.setText("70%");
        jPanel4.add(cloudCover);
        cloudCover.setBounds(240, 190, 80, 21);

        humidityImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/humidity_mid_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jPanel4.add(humidityImage);
        humidityImage.setBounds(20, 180, 20, 20);

        windspeeds.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        windspeeds.setText("7Km/h");
        jPanel4.add(windspeeds);
        windspeeds.setBounds(50, 260, 90, 21);

        windspeedText.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        windspeedText.setForeground(new java.awt.Color(102, 102, 102));
        windspeedText.setText("Tốc độ gió");
        jPanel4.add(windspeedText);
        windspeedText.setBounds(50, 240, 83, 23);

        humidityText.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        humidityText.setForeground(new java.awt.Color(102, 102, 102));
        humidityText.setText("Độ ẩm");
        jPanel4.add(humidityText);
        humidityText.setBounds(50, 170, 60, 24);

        windspeedImage.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        windspeedImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/air_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        windspeedImage.setToolTipText("");
        jPanel4.add(windspeedImage);
        windspeedImage.setBounds(20, 240, 24, 24);

        humidityPercent.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        humidityPercent.setText("70%");
        jPanel4.add(humidityPercent);
        humidityPercent.setBounds(50, 190, 60, 21);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Nhiệt độ đất");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(240, 240, 96, 23);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        weatherConditionDesc.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        weatherConditionDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weatherConditionDesc.setText("Trời trong xanh");
        weatherConditionDesc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(weatherConditionDesc);
        weatherConditionDesc.setBounds(180, 87, 180, 32);

        temperatureText.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        temperatureText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureText.setText("28℃");
        jPanel7.add(temperatureText);
        temperatureText.setBounds(170, 40, 200, 40);

        weatherConditionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear128.png"))); // NOI18N
        weatherConditionImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        weatherConditionImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        weatherConditionImage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel7.add(weatherConditionImage);
        weatherConditionImage.setBounds(50, 10, 130, 128);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(0, 0, 390, 157);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(26, 70, 390, 300);

        jPanel5.setBackground(new java.awt.Color(130, 180, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DỰ BÁO TRONG 3 NGÀY TỚI");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(26, 390, 390, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("12/12/2023");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(6, 39, 90, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("13/12/2023");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(6, 77, 80, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("14/12/2023");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(6, 115, 80, 20);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clearmini.png"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(120, 40, 20, 20);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clearmini.png"))); // NOI18N
        jPanel3.add(jLabel19);
        jLabel19.setBounds(120, 70, 20, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clearmini.png"))); // NOI18N
        jPanel3.add(jLabel20);
        jLabel20.setBounds(120, 110, 20, 30);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("18℃");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(187, 42, 50, 16);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("28℃");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(312, 42, 50, 16);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("17℃");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(187, 80, 50, 16);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("38℃");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(312, 80, 50, 16);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("19℃");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(187, 118, 50, 16);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("23℃");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(300, 114, 70, 20);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel27.setText("NGÀY");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(30, 14, 28, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel28.setText("NHIỆT ĐỘ THẤP NHẤT");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(160, 10, 110, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel29.setText("NHIỆT ĐỘ CAO NHẤT");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(280, 10, 110, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(26, 420, 390, 150);

        myLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myLocation.setText("LOCATION NAME");
        jPanel1.add(myLocation);
        myLocation.setBounds(40, 40, 160, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(417, 600, 37, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setIcon(String key, JLabel label, String path1, String path2,String path3,String path4){
        String weatherCondition = (String) weatherData.get(key);

        switch (weatherCondition){
            case "Trời quang đãng":
                
            label.setIcon(new javax.swing.ImageIcon(path1));            
            break;
            case "Có mây":
            label.setIcon(new javax.swing.ImageIcon(path2));           
            break;
            case "Có mưa":
            label.setIcon(new javax.swing.ImageIcon(path3));           
            break;
            case "Có tuyết":
            label.setIcon(new javax.swing.ImageIcon(path4));           
            break;
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://DESKTOP-A9JVF1E\\SQLEXPRESS:1433;databaseName=Location;user=sa;password=12";
                Connection con = DriverManager.getConnection(dbUrl);
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("select * from DiaDiem");
                if(rs.next()){
                
                    //jPanel8.setVisible(true);
        
                   
                    myLocation.setText(rs.getString(2).trim().toUpperCase());

                    weatherData = WeatherApp.getWeatherData(rs.getString(2).trim());
                    
                }
                
                con.close();
                }catch(ClassNotFoundException ex){
                    ex.printStackTrace();
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
        
//        setIcon("weather_condition", weatherConditionImage, "src/image/clear128.png","src/image/cloudy128.png", "src/image/rainy128.png", "src/image/snow128.png");
        String weatherCondition = (String) weatherData.get("weather_condition");
        long str = (long) weatherData.get("isDay");
        if(str == 1){
            jLabel2.setIcon(new javax.swing.ImageIcon("src/image/day.png"));
            
        }else jLabel2.setIcon(new javax.swing.ImageIcon("src/image/night.png"));
        
        if (weatherCondition.equals("Trời quang đãng") && str==1) {
           
            weatherConditionImage.setIcon(new javax.swing.ImageIcon("src/image/clear128.png"));            
        }else weatherConditionImage.setIcon(new javax.swing.ImageIcon("src/image/moon128.png")); 
        switch (weatherCondition){
            
            case "Có mây":
            weatherConditionImage.setIcon(new javax.swing.ImageIcon("src/image/cloudy128.png"));           
            break;
            case "Có mưa":
            weatherConditionImage.setIcon(new javax.swing.ImageIcon("src/image/rainy128.png"));           
            break;
            case "Có tuyết":
            weatherConditionImage.setIcon(new javax.swing.ImageIcon("src/image/snow128.png"));           
            break;
        }
        
        setIcon("weather_condition1", jLabel18, "src/image/clearmini.png","src/image/cloudmini.png", "src/image/rainymini.png", "src/image/snowmini.png");
        setIcon("weather_condition2", jLabel19, "src/image/clearmini.png","src/image/cloudmini.png", "src/image/rainymini.png", "src/image/snowmini.png");
        setIcon("weather_condition3", jLabel20, "src/image/clearmini.png","src/image/cloudmini.png", "src/image/rainymini.png", "src/image/snowmini.png");
        
        
        weatherConditionDesc.setText((String) weatherData.get("weather_condition"));
        double temperature = (double) weatherData.get("temperature");
        temperatureText.setText(temperature + "℃");
        long humidity = (long) weatherData.get("humidity");
        humidityPercent.setText(humidity + " %");
        
        double windspeed = (double) weatherData.get("windspeed");
        windspeeds.setText(windspeed + "km/h");
       
        long cloudCoverData = (long) weatherData.get("cloudCoverData");
        cloudCover.setText(cloudCoverData + "%");
        
        double soilTemperatureData = (double) weatherData.get("soilTemperature");
        soilTemperature.setText(soilTemperatureData + "℃");
        
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatterDate = DateTimeFormatter.ofPattern("dd-MM-yyyy");
       
        String formattedDateTime = currentDate.format(formatterDate);
        
        jLabel3.setText(formattedDateTime.substring(0, 10));
       
        

        String date1 = (String) weatherData.get("date1");
        jLabel15.setText(date1);
        String date2 = (String) weatherData.get("date2");
        jLabel16.setText(date2);
        String date3 = (String) weatherData.get("date3");
        jLabel17.setText(date3);
        
        double temperatureMax1 = (double) weatherData.get("temperatureMax1");
        jLabel22.setText(temperatureMax1 + " ℃");
        double temperatureMax2 = (double) weatherData.get("temperatureMax2");
        jLabel24.setText(temperatureMax2 + " ℃");
        double temperatureMax3 = (double) weatherData.get("temperatureMax3");
        jLabel26.setText(temperatureMax3 + " ℃");
        
        
        double temperatureMin1 = (double) weatherData.get("temperatureMin1");
        jLabel21.setText(temperatureMin1 + " ℃");
        double temperatureMin2 = (double) weatherData.get("temperatureMin2");
        jLabel23.setText(temperatureMin2 + " ℃");
        double temperatureMin3 = (double) weatherData.get("temperatureMin3");
        jLabel25.setText(temperatureMin3 + " ℃");
    }//GEN-LAST:event_formWindowOpened

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new WeatherGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyWeatherGUI().setVisible(true);               
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cloudCover;
    private javax.swing.JLabel humidityImage;
    private javax.swing.JLabel humidityPercent;
    private javax.swing.JLabel humidityText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel myLocation;
    private javax.swing.JLabel soilTemperature;
    private javax.swing.JLabel temperatureText;
    private javax.swing.JLabel weatherConditionDesc;
    private javax.swing.JLabel weatherConditionImage;
    private javax.swing.JLabel windspeedImage;
    private javax.swing.JLabel windspeedText;
    private javax.swing.JLabel windspeeds;
    // End of variables declaration//GEN-END:variables
}
